# Generated by Django 4.1.4 on 2023-03-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_expenses_status_doc_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='exp_type',
            field=models.CharField(default='exp', max_length=20),
        ),
    ]
