# Generated by Django 4.1.4 on 2023-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_dayclose'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashInHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_in', models.BigIntegerField()),
            ],
        ),
    ]
