# Generated by Django 4.1.4 on 2023-03-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_cashinhand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashinhand',
            old_name='cash_in',
            new_name='amount',
        ),
    ]
