# Generated by Django 4.1.4 on 2023-03-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_cash_in_cashinhand_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashInHand',
            new_name='InHand',
        ),
    ]
