# Generated by Django 4.1.4 on 2023-03-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_cashinhand_inhand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_InHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='InHand',
        ),
    ]
