# Generated by Django 4.1.4 on 2023-03-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_cash_inhand_delete_inhand'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField()),
                ('deposite', models.BigIntegerField()),
                ('disc', models.CharField(max_length=50)),
            ],
        ),
    ]
