# Generated by Django 4.1.7 on 2023-03-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_bankdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_op',
            name='disc',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
