# Generated by Django 4.1.7 on 2023-03-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_doc_op_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_op',
            name='date',
            field=models.DateField(default='2023-03-21'),
            preserve_default=False,
        ),
    ]
